apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-acg
  region: us-west-2
  version: "1.27"

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: HighlyAvailable
nodeGroups:
  - name: eks-node-group
    instanceType: t3.medium
    desiredCapacity: 3
    privateNetworking: true
    volumeSize: 30

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"] # This is required since in us-east-1 only 2 subnets are created by default (https://eksctl.io/usage/vpc-networking/)
